@startuml サンプルRPG
package キャラクター {
object プレイヤー
object 敵
object NPC
}
package ワールドマップ {
object ベクトル
object タイル
object アニメーション
object 位置
object 方向
object 衝突
}
package 戦闘 {
object 戦闘
object ヒットポイント
object 攻撃力
object 魔法力
object 防御力
object レベル
object 経験値
object 技
object 物理攻撃
object 魔法攻撃
}
package アイテム {
object 装備
object 回復薬
object 鍵
object プレイヤーの所持品
}
プレイヤー -- ヒットポイント
プレイヤー -- 攻撃力
プレイヤー -- 魔法力
プレイヤー -- 防御力
プレイヤー -- 技
プレイヤー -- アニメーション
プレイヤー -- 位置
プレイヤー -- 装備
プレイヤー -- 衝突
プレイヤー -- プレイヤーの所持品
プレイヤー -- レベル
プレイヤー -- 経験値
敵 -- ヒットポイント
敵 -- 攻撃力
敵 -- 経験値
敵 -- アニメーション
敵 -- 位置
敵 -- 衝突
NPC -- 位置
NPC -- アニメーション
NPC -- 衝突
装備 -- 攻撃力
装備 -- 魔法力
装備 -- 防御力
プレイヤーの所持品 -- 装備
プレイヤーの所持品 -- 回復薬
プレイヤーの所持品 -- 鍵
戦闘 -- プレイヤー
戦闘 -- 敵
技 -- 物理攻撃
技 -- 魔法攻撃
@enduml