/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sample;

import javax.swing.*;

public class App {
  public static void main(String[] args) {
    JFrame window = new JFrame();
    window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    window.setResizable(false);
    window.setTitle("2D Adventure");
  
    GamePanel gamePanel = new GamePanel();
    gamePanel.setFocusable(true);
    window.add(gamePanel);
  
    window.pack();
  
    window.setLocationRelativeTo(null);
    window.setVisible(true);
  
    gamePanel.setupGame();
    gamePanel.startGameThread();
  }
}
