///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package com.example.sample;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//
//public class BadCodeSampleApplicationTest {
//    @Test public void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
//}
