/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sample;

public class GoodCodeSampleApplication {
  public static void main(String[] args) {
    System.out.println("Good Code Sample!");
  }
}
